<?php
function acmod_form_alter(&$form, &$form_state, $form_id) {
	//dsm($form);
	if(isset($form['#importer_id']) && ($form['#importer_id'] == 'importateur_agglomerations' || $form['#importer_id'] == 'importateur_wwtp' || $form['#importer_id'] == 'importateur_discharge_points' || $form['#importer_id'] == 'importateur_discharge_points' || $form['#importer_id'] == 'importateur_receiving_area')){
		$year = date("Y");
		$years = array(
			'2000' => '2000', 
			'2001' => '2001', 
			'2002' => '2002', 
			'2003' => '2003', 
			'2004' => '2004', 
			'2005' => '2005', 
			'2006' => '2006', 
			'2007' => '2007', 
			'2008' => '2008', 
			'2009' => '2009', 
			'2010' => '2010', 
			'2011' => '2011', 
			'2012' => '2012', 
			'2013' => '2013', 
			'2014' => '2014', 
			'2015' => '2015', 
			'2016' => '2016', 
			'2017' => '2017', 
			'2018' => '2018', 
			'2019' => '2019', 
			'2020' => '2020'
		);
		$form['feeds_annee'] = array(     
			'#type' => 'select',
			'#title' => t('Année'),
			'#default_value' => $year,        
			'#options' => $years,
			'#weight' => 0,
		);
		$form['#submit'][] = 'acmod_submit_handler';
	}
}

function acmod_submit_handler($form, &$form_state) {
	global $anneeFeeds;
	$annee = variable_set('feeds_annee', ($form_state['values']['feeds_annee']));
}