<strong>The information on this site is subject to a disclaimer, a copyright notice and rules related to personal data protection.</strong>

<strong>Disclaimer</strong>

This website is launched in the framework of Specific contract n°07.0307/2012/638595/D2 implementing Framework Service Contract n°ENV.D.2/FRA/2012/0013 for the European Commission, however it reflects the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein.

The Office International de l’Eau maintains this website to enhance public access to information:

- reported to the European Commission for the implementation of Directive 91/271/EC by [#COUNTRY#]
- or gathered at the national level in view of reporting between reporting periods,
- or gathered or available at national level for use by national authorities.

Our goal is to keep this information timely and accurate. If errors are brought to our attention, we will try to correct them. However, the Office International de l’Eau accepts no responsibility or liability whatsoever with regard to the information on this site.

This information is:

  • of a general nature only and is not intended to address the specific circumstances of any particular individual or entity; 
  • not necessarily comprehensive, complete, accurate or up to date; 
  • sometimes linked to external sites over which Office International de l’Eau and DG Environment have no control and for which Office International de l’Eau and DG Environment assume no responsibility; 
  • not professional or legal advice (if you need specific advice, you should always consult a suitably qualified professional). 

It is our goal to minimize disruption caused by technical errors. However some data or information on this site may have been created or structured in files or formats that are not error-free and we cannot guarantee that our service will not be interrupted or otherwise affected by such problems. Office International de l’Eau accepts no responsibility with regard to such problems incurred as a result of using this site or any linked external sites.

This disclaimer is not intended to limit the liability of Office International de l’Eau in contravention of any requirements laid down in applicable national law nor to exclude its liability for matters which may not be excluded under that law.

<strong>Copyright notice</strong>
 
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">UWWTD-SIIF platform</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="uwwtd.oieau.fr" property="cc:attributionName" rel="cc:attributionURL">Office International de l'Eau</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.<br />Permissions beyond the scope of this license may be available at <a xmlns:cc="http://creativecommons.org/ns#" href="www.oieau.fr" rel="cc:morePermissions">www.oieau.fr</a>

This website is the property of UWWTD-SIIF project, a DGENV project lead by the UmweltBundesamt Austria in consortium with Office International de l’Eau - 15 rue E. Chamberland - 87065 Limoges Cedex - France

Contact:  contact@uwwtd.oieau.fr  – Project manager: Benoît Fribourg-blanc - Telephone: +33-(0)555 11 47 80

The general reproduction structure of texts, animated images or otherwise and any other component of the Website are the sole property of DG Environment. Any total or partial representation of this Website by any process whatsoever without the express authorization of the Natural Water Retention Measures project is forbidden and shall constitute unauthorized reproduction penalized by articles L.335-2 et seq. of the Code of intellectual property under French law.

All of the rights of reproduction are reserved, including downloadable documents (logos, photos, catalogues, booklets, brochures, and any type of information whatsoever...). Downloadable documents are also protected by copyright.

Similarly, databases appearing on the Website, which is protected by the provisions of the Intellectual Property Code concerning incorporation of the European directive of March 11, 1996 regarding the legal protection of databases produced by Office International de l’Eau.

User or visitor of the Website are encouraged to install a hyperlink to this Website and inform Office International de l’Eau.

The reuse is subject to the reuse policy of the European Commission implemented by a <a href="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2011:330:0039:0042:EN:PDF">Decision of 12 December 2011</a>.

<strong>Personal Data Protection</strong>

As the user, you are informed, in accordance with French law of January 6. 1978 and its article 27 on the protection of data, files and civil liberties, that any optional data you may choose to provide when completing the forms located on the Website allowing us to respond to your request, are solely intended for the UWWTD SIIF project, which is responsible for the processing of the data, for administrative and business management purposes.

You are informed that you have a right to access and rectify all personal data regarding you by writing to the Office International de l’Eau - 15 rue E. Chamberland - 87065 Limoges Cedex - France

The UWWTD SIIF project is committed to European Union policy on user privacy.

The policy on "protection of individuals with regard to the processing of personal data by the Community institutions" is based on Regulation (EC) N° 45/2001 of the European Parliament and of the Council of 18 December 2000. 

Although you can browse through most of the current website without giving any information about yourself, in some cases, personal information is required. Such information will be treated it according to the policy described in the Regulation mentioned above and the specific objective described on the website form, focussing mainly on providing interactive communication services and possibilities for a registered user to contribute to the project.
 
The specific privacy policy statement of this website is the following:

  • We collect via the contact form your contact details and fields of expertise and/or interest to allow us involve you in the improvement of the website. The information will not be re-used for an incompatible purpose; 
  •  Your information is solely disclosed to the partners of the UWWTD SIIF  project and national authority of the country. We will only disclose information to third parties if that is necessary for the fulfilment of the purpose(s) identified above. We will not divulge your personal data for direct marketing purposes; 
  • By clicking on the “Send message” you give your unambiguous consent to UWWTD SIIF project to use your data for the above purpose.
  • Your data will be kept by the UWWTD SIIF project for the duration of the project (December 2013-March 2015) and transferred to the public authority that will take over responsibility of the website.
  • If you have queries or complaints, please contact the webmaster at contact@uwwtd.oieau.fr  

How do we treat e-mails you send us? 

When using the "Contact" button, you activate a specific form that invites you to send your comments to a specific functional mailbox. 

When you send such a message, your personal data is collected only to the extent necessary to reply. If the management team of the mailbox is unable to answer your question, it will forward your e-mail to another expert. You will be informed, via e-mail, about which expert your question has been forwarded to. 

If you have any questions about the processing of your e-mail and related personal data, do not hesitate to include them in your message.

<strong>Creation, development, hosting and management of the website</strong>
Office International de l’Eau (OIEau) for UWWTD SIIF project
 
<strong>Copyrights</strong>
 
UWWTD-SIIF platform by Office International de l'Eau is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.
Permissions beyond the scope of this license may be available at www.oieau.fr.

<strong>Contact</strong>
Office International de l’Eau (OIEau)
15 rue Edouard Chamberland 87065 LIMOGES cedex
 
<strong>Webmaster</strong>
b.fribourg-blanc[at]oieau.fr
                              