

<p><strong><em>TO BE COMPLETED.</em> </strong></p>
<h3>Get the datasets</h3>
<p>On this page you will find the useful links to get the datasets used on this platform in various formats (<strong>xls</strong>, <strong>csv</strong>, <strong>kml</strong>, shp, WFS…) in order to use these data on other softwares for your own purpose.</p>
<p>&nbsp;</p>
<h3>Webservices - WFS</h3>
<p><strong>DescribeFeatureType</strong>: description of the information layers, name and type of fields.</p>
<ul>
   <li>Agglomeration<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_France_Agglomeration" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_France_Agglomeration</a></li>
</ul>
<ul>
   <li>DischargePoint<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_France_DischargePoint" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_France_DischargePoint</a></li>
</ul>
<ul>
   <li>ReceivingArea<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_France_ReceivingArea" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_France_ReceivingArea</a></li>
</ul>
<ul>
   <li>UrbanWasteWaterTreatmentPlant<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_France_UrbanWasteWaterTreatmentPlant" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_France_UrbanWasteWaterTreatmentPlant</a></li>
</ul>
<p>&nbsp;</p>
<p><strong>GetFeature</strong>: access to data in GML format</p>
<ul>
   <li>Agglomeration<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_France_Agglomeration&amp;MaxFeature=5" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_France_Agglomeration&amp;MaxFeature=5</a></li>
</ul>
<ul>
   <li>DischargePoint<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_France_DischargePoint&amp;MaxFeature=5" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_France_DischargePoint&amp;MaxFeature=5</a></li>
</ul>
<ul>
   <li>ReceivingArea<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_France_ReceivingArea&amp;MaxFeature=5" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_France_ReceivingArea&amp;MaxFeature=5</a></li>
</ul>
<ul>
   <li>UrbanWasteWaterTreatmentPlant<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_France_UrbanWasteWaterTreatmentPlant&amp;MaxFeature=5" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_France_UrbanWasteWaterTreatmentPlant&amp;MaxFeature=5</a></li>
</ul>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h3>How to make references to this website ?</h3>
<p>All the items description page (agglomeration, treatment plant, discharge point and sensitive areas) can be accessed directly, and then referenced on other websites.</p>
<p>This can be done by using the following URL pattern: http://uwwtd.oieau.fr/france/[year]/[name of the element]/[ID of the element];<br />For instance:</p>
<ul>
   <li>http://uwwtd.oieau.fr/france/agglomeration/fr030000175056/2012</li>
   <li>http://uwwtd.oieau.fr/france/treatment-plant/fr039407401000/2012</li>
   <li>http://uwwtd.oieau.fr/france/discharge-point/fr039407401000r1/2012</li>
</ul>
<p>&nbsp;</p>



<h3><strong>Europe</strong></h3>
<h4>Directorate General Environment</h4>
<ul>
   <li>DGENV website&nbsp; : <a href="http://ec.europa.eu/environment/water/water-urbanwaste/index_en.html" target="_blank">http://ec.europa.eu/environment/water/water-urbanwaste/index_en.html</a></li>
</ul>
<ul>
   <li>Implementation reports <a href="http://ec.europa.eu/environment/water/water-urbanwaste/implementation/implementationreports_en.htm" target="_blank">http://ec.europa.eu/environment/water/water-urbanwaste/implementation/implementationreports_en.htm</a></li>
</ul>
<h4>European Environment Agency</h4>
<p><strong>Reporting Obligation Database (ROD):</strong></p>
<ul>
   <li>UWWT Directive fiche <a href="http://rod.eionet.europa.eu/instruments/543" target="_blank">http://rod.eionet.europa.eu/instruments/543</a></li>
   <li>National Implementation Programme for UWWT Directive - Article 17&nbsp; <a href="http://rod.eionet.europa.eu/obligations/524" target="_blank">http://rod.eionet.europa.eu/obligations/524</a></li>
   <li>UWWT Directive - Article 16 - Situation report&nbsp;&nbsp; <a href="http://rod.eionet.europa.eu/obligations/387" target="_blank">http://rod.eionet.europa.eu/obligations/387</a></li>
   <li>UWWT Directive - Article 15 - implementation&nbsp; <a href="http://rod.eionet.europa.eu/obligations/613" target="_blank">http://rod.eionet.europa.eu/obligations/613</a></li>
</ul>
<p><strong>Access to data and visualisation</strong></p>
<ul>
   <li>Waterbase UWWTD <a href="http://www.eea.europa.eu/data-and-maps/data/waterbase-uwwtd-urban-waste-water-treatment-directive" target="_blank">http://www.eea.europa.eu/data-and-maps/data/waterbase-uwwtd-urban-waste-water-treatment-directive</a></li>
   <li>UWWTD EU viewer <a href="http://www.eea.europa.eu/data-and-maps/uwwtd/interactive-maps/urban-waste-water-treatment-maps" target="_blank">http://www.eea.europa.eu/data-and-maps/uwwtd/interactive-maps/urban-waste-water-treatment-maps</a></li>
</ul>
<h3><br />France</h3>
<ul>
   <li>to be completed</li>
</ul>
<p style="padding-left: 30px;">&nbsp;</p>
<h3>Other National UWWTD SIIF</h3>
<ul>
   <li>Generic platform: <a href="http://uwwtd.oieau.fr/" target="_blank">http://uwwtd.oieau.fr/</a></li>
   <li>Croatia: <a href="http://uwwtd.oieau.fr/croatia/" target="_blank">http://uwwtd.oieau.fr/croatia/</a></li>
   <li>Cyprus: <a href="http://uwwtd.oieau.fr/cyprus/" target="_blank">http://uwwtd.oieau.fr/cyprus/</a></li>
   <li>Lithuania : <a href="http://uwwtd.oieau.fr/lithuania/" target="_blank">http://uwwtd.oieau.fr/lithuania/</a></li>
   <li>Poland: <a href="http://uwwtd.oieau.fr/poland/" target="_blank">http://uwwtd.oieau.fr/poland/</a></li>
   <li>Romania: <a href="http://uwwtd.oieau.fr/romania/" target="_blank">http://uwwtd.oieau.fr/romania/</a></li>
</ul>
<p style="padding-left: 30px;">&nbsp;</p>

