

<p><strong><em>TO BE COMPLETED.</em> </strong></p>
<h3>Get the datasets</h3>
<p>On this page you will find the useful links to get the datasets used on this platform in various formats (<strong>xls</strong>, <strong>csv</strong>, <strong>kml</strong>, shp, WFS…) in order to use these data on other softwares for your own purpose.</p>
<p>&nbsp;</p>
<h3>Webservices - WFS</h3>
<p><strong>DescribeFeatureType</strong>: description of the information layers, name and type of fields.</p>
<ul>
   <li>Agglomeration<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_Cyprus_Agglomeration" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_Cyprus_Agglomeration</a></li>
</ul>
<ul>
   <li>DischargePoint<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_Cyprus_DischargePoint" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_Cyprus_DischargePoint</a></li>
</ul>
<ul>
   <li>ReceivingArea<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_Cyprus_ReceivingArea" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_Cyprus_ReceivingArea</a></li>
</ul>
<ul>
   <li>UrbanWasteWaterTreatmentPlant<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_Cyprus_UrbanWasteWaterTreatmentPlant" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=DescribeFeatureType&amp;TypeName=UWWTD:UWWTD_Cyprus_UrbanWasteWaterTreatmentPlant</a></li>
</ul>
<p>&nbsp;</p>
<p><strong>GetFeature</strong>: access to data in GML format</p>
<ul>
   <li>Agglomeration<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_Cyprus_Agglomeration&amp;MaxFeature=5" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_Cyprus_Agglomeration&amp;MaxFeature=5</a></li>
</ul>
<ul>
   <li>DischargePoint<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_Cyprus_DischargePoint&amp;MaxFeature=5" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_Cyprus_DischargePoint&amp;MaxFeature=5</a></li>
</ul>
<ul>
   <li>ReceivingArea<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_Cyprus_ReceivingArea&amp;MaxFeature=5" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_Cyprus_ReceivingArea&amp;MaxFeature=5</a></li>
</ul>
<ul>
   <li>UrbanWasteWaterTreatmentPlant<br /><a href="http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_Cyprus_UrbanWasteWaterTreatmentPlant&amp;MaxFeature=5" target="_blank">http://www.uwwtd.oieau.fr/services/wfs/?service=WFS&amp;version=1.1.0&amp;request=GetFeature&amp;TypeName=UWWTD:UWWTD_Cyprus_UrbanWasteWaterTreatmentPlant&amp;MaxFeature=5</a></li>
</ul>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h3>How to make references to this website ?</h3>
<p>All the items description page (agglomeration, treatment plant, discharge point and sensitive areas) can be accessed directly, and then referenced on other websites.</p>
<p>This can be done by using the following URL pattern: http://uwwtd.oieau.fr/Cyprus/[year]/[name of the element]/[ID of the element];<br />For instance:</p>
<ul>
   <li>http://uwwtd.oieau.fr/cyprus/agglomeration/cy11-agglo/2011</li>
   <li>http://uwwtd.oieau.fr/cyprus/treatment-plant/cy11_3_uwwtp/2011</li>
   <li>http://uwwtd.oieau.fr/cyprus/discharge-point/cy11_3-dispoint2/2011</li>
</ul>
<p>&nbsp;</p>

