<?php 

$virtual = array (
  'view_modes' => 
  array (
    'teaser' => 
    array (
      'custom_settings' => true,
    ),
    'full' => 
    array (
      'custom_settings' => false,
    ),
    'rss' => 
    array (
      'custom_settings' => false,
    ),
    'search_index' => 
    array (
      'custom_settings' => false,
    ),
    'search_result' => 
    array (
      'custom_settings' => false,
    ),
    'token' => 
    array (
      'custom_settings' => false,
    ),
  ),
  'extra_fields' => 
  array (
    'form' => 
    array (
    ),
    'display' => 
    array (
      'virtual_field_map' => 
      array (
        'default' => 
        array (
          'weight' => '1',
          'visible' => true,
        ),
      ),
      'virtual_compliance_time_line' => 
      array (
        'default' => 
        array (
          'weight' => '20',
          'visible' => true,
        ),
      ),
      'virtual_field_aggc1_with_pe' => 
      array (
        'default' => 
        array (
          'weight' => '9',
          'visible' => true,
        ),
      ),
      'virtual_field_aggc2_with_pe' => 
      array (
        'default' => 
        array (
          'weight' => '10',
          'visible' => true,
        ),
      ),
      'virtual_field_aggpercwithouttreatment_with_pe' => 
      array (
        'default' => 
        array (
          'weight' => '11',
          'visible' => true,
        ),
      ),
      'virtual_field_piechart_agglonode' => 
      array (
        'default' => 
        array (
          'weight' => '12',
          'visible' => true,
        ),
      ),
      'virtual_field_aggart4compliance_hierarchical' => 
      array (
        'default' => 
        array (
          'weight' => '25',
          'visible' => true,
        ),
      ),
      'virtual_field_aggart5compliance_hierarchical' => 
      array (
        'default' => 
        array (
          'weight' => '26',
          'visible' => true,
        ),
      ),
      'virtual_field_table_distance_to_compliance' => 
      array (
        'default' => 
        array (
          'weight' => '27',
          'visible' => true,
        ),
      ),
      'virtual_field_latitude_custom' => 
      array (
        'default' => 
        array (
          'weight' => '22',
          'visible' => true,
        ),
      ),
      'virtual_field_longitude_custom' => 
      array (
        'default' => 
        array (
          'weight' => '23',
          'visible' => true,
        ),
      ),
      'virtual_field_aggperiodover5_custom' => 
      array (
        'default' => 
        array (
          'weight' => '26',
          'visible' => true,
        ),
      ),
      'virtual_field_source_file_link' => 
      array (
        'default' => 
        array (
          'weight' => '34',
          'visible' => true,
        ),
      ),
      'virtual_field_article_17' => 
      array (
        'default' => 
        array (
          'weight' => '11',
          'visible' => true,
        ),
      ),
      'virtual_field_error' => 
      array (
        'default' => 
        array (
          'weight' => '0',
          'visible' => true,
        ),
      ),
      'virtual_graphic' => 
      array (
        'default' => 
        array (
          'weight' => '26',
          'visible' => true,
        ),
      ),
    ),
  ),
);