<?php 

$groups = array (
  'form' => 
  array (
    'group_agg_system' => 
    (object)(array(
       'id' => '45',
       'identifier' => 'group_agg_system|node|agglomeration|form',
       'group_name' => 'group_agg_system',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'form',
       'parent_name' => 'group_agg_admin',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'disabled' => false,
       'label' => 'System',
       'weight' => '136',
       'children' => 
      array (
        0 => 'field_region_nuts3',
        1 => 'field_agg_equip_met_ms',
        2 => 'field_region_nuts1',
        3 => 'field_agg_ias_load_pe',
        4 => 'field_dtt_art_4_treatment',
        5 => 'field_agg_perf_met_ms',
        6 => 'field_agg_connected_load_pe',
        7 => 'field_agg_discharge_pe',
        8 => 'field_dtt_art_5_performance',
        9 => 'field_dtt_art_5_treatment',
        10 => 'field_dtt_art3',
        11 => 'field_agg_equip_ms',
        12 => 'field_repcode',
        13 => 'field_agg_perf_s',
        14 => 'field_agg_perf_ms',
        15 => 'field_agg_equip_s',
        16 => 'field_dtt_art_4_performance',
        17 => 'field_anneedata',
        18 => 'field_region_nuts2',
        19 => 'field_sourcefile',
      ),
       'format_type' => 'tab',
       'format_settings' => 
      array (
        'formatter' => 'closed',
        'instance_settings' => 
        array (
          'description' => '',
          'classes' => '',
          'required_fields' => 1,
        ),
      ),
    )),
    'group_agg_deprecated' => 
    (object)(array(
       'id' => '47',
       'identifier' => 'group_agg_deprecated|node|agglomeration|form',
       'group_name' => 'group_agg_deprecated',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'form',
       'parent_name' => 'group_agg_admin',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'disabled' => false,
       'label' => 'Deprecated fields',
       'weight' => '137',
       'children' => 
      array (
        0 => 'field_aggdatecompliance5',
        1 => 'field_sourceofname',
        2 => 'field_aggcritcb',
        3 => 'field_inspireidversionid',
        4 => 'field_agginhabitantsconnectedias',
        5 => 'field_agg_bc_morestringet_other',
        6 => 'field_namepronunciation',
        7 => 'field_aggcritb',
        8 => 'field_agg_bc_secondary',
        9 => 'field_namelanguage',
        10 => 'field_agg_connected_load_feed',
        11 => 'field_thematicid',
        12 => 'field_environmentaldomain1',
        13 => 'field_namegrammaticalgender',
        14 => 'field_agg_bc_primary',
        15 => 'field_designationperiod',
        16 => 'field_aggdatecompliance3',
        17 => 'field_documentationcitation',
        18 => 'field_region_nuts1_feed',
        19 => 'field_endlifespanversion',
        20 => 'field_aggdatecompliance4',
        21 => 'field_agg_bc_notreatment',
        22 => 'field_agginhabitant',
        23 => 'field_region_nuts3_feed',
        24 => 'field_namenativeness',
        25 => 'field_specialisedzonetype',
        26 => 'field_legislationcitation',
        27 => 'field_region_nuts2_feed',
        28 => 'field_beginlifespanversion',
        29 => 'field_agg_bc_morestringet_np',
        30 => 'field_namestatus',
        31 => 'field_namegrammaticalnumber',
        32 => 'field_inspireidnamespace',
        33 => 'field_aggdateexported',
        34 => 'field_agg_ias_load_feed',
        35 => 'field_competentauthority',
        36 => 'field_sensitiveareatype',
        37 => 'field_environmentaldomain2',
        38 => 'field_agg_typeof_sa',
        39 => 'field_aggdatecompliance6',
        40 => 'field_aggcritca',
        41 => 'field_agginhabitantswithouttreat',
      ),
       'format_type' => 'tab',
       'format_settings' => 
      array (
        'formatter' => 'closed',
        'instance_settings' => 
        array (
          'description' => '',
          'classes' => 'group-agg-deprecated field-group-tab',
          'required_fields' => 1,
        ),
      ),
    )),
    'group_agg_links' => 
    (object)(array(
       'id' => '44',
       'identifier' => 'group_agg_links|node|agglomeration|form',
       'group_name' => 'group_agg_links',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'form',
       'parent_name' => 'group_agg_admin',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'disabled' => false,
       'label' => 'Links',
       'weight' => '135',
       'children' => 
      array (
        0 => 'field_agguwwliste',
        1 => 'field_rcadcpliste',
        2 => 'field_zonetype',
        3 => 'field_linked_treatment_plants',
        4 => 'field_linked_receiving_areas',
        5 => 'field_sensitivearealink',
        6 => 'field_regionnuts',
        7 => 'field_linked_discharge_points',
        8 => 'field_agg_rbd_code',
        9 => 'field_aggbigid',
        10 => 'field_aggbcliste',
        11 => 'field_article17_agglo',
      ),
       'format_type' => 'tab',
       'format_settings' => 
      array (
        'formatter' => 'closed',
        'instance_settings' => 
        array (
          'description' => '',
          'classes' => '',
          'required_fields' => 1,
        ),
      ),
    )),
    'group_agg_description' => 
    (object)(array(
       'id' => '42',
       'identifier' => 'group_agg_description|node|agglomeration|form',
       'group_name' => 'group_agg_description',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'form',
       'parent_name' => 'group_agg_admin',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'disabled' => false,
       'label' => 'Description',
       'weight' => '133',
       'children' => 
      array (
        0 => 'field_aggforecast',
        1 => 'field_aggpercsectreatment',
        2 => 'field_aggaccoverflownumber',
        3 => 'field_aggendlife',
        4 => 'field_aggseweroverflows_m3',
        5 => 'field_aggmethodc2',
        6 => 'field_agghaveregistrationsystem',
        7 => 'field_agggenerated',
        8 => 'field_siteid',
        9 => 'field_aggvideoinspections',
        10 => 'field_aggmethodc1',
        11 => 'field_aggc1',
        12 => 'field_aggpercwithouttreatment',
        13 => 'field_aggbesttechnicalknowledge',
        14 => 'field_inspireidlocalid',
        15 => 'field_aggaccoverflows',
        16 => 'field_aggcalculation',
        17 => 'field_aggsuccessor',
        18 => 'field_aggothermeasures',
        19 => 'field_aggpressuretest',
        20 => 'field_aggcapacity',
        21 => 'field_aggchanges',
        22 => 'field_agg_dilution_rates',
        23 => 'field_aggexplanationother',
        24 => 'field_aggmunicipalities',
        25 => 'field_aggseweroverflows_pe',
        26 => 'field_aggpercprimtreatment',
        27 => 'field_position_geo',
        28 => 'field_aggsewagenetwork',
        29 => 'field_aggpercstringenttreatment',
        30 => 'field_agglatitude',
        31 => 'field_aggremarks',
        32 => 'field_aggchangescomment',
        33 => 'field_aggc2',
        34 => 'field_aggnathyperlink',
        35 => 'field_aggbeginlife',
        36 => 'field_status',
        37 => 'field_aggexistmaintenanceplan',
        38 => 'field_aggmethodwithouttreatment',
        39 => 'field_agglongitude',
        40 => 'title',
      ),
       'format_type' => 'tab',
       'format_settings' => 
      array (
        'formatter' => 'closed',
        'instance_settings' => 
        array (
          'description' => '',
          'classes' => '',
          'required_fields' => 1,
        ),
      ),
    )),
    'group_agg_compliance' => 
    (object)(array(
       'id' => '43',
       'identifier' => 'group_agg_compliance|node|agglomeration|form',
       'group_name' => 'group_agg_compliance',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'form',
       'parent_name' => 'group_agg_admin',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'disabled' => false,
       'label' => 'Compliance',
       'weight' => '134',
       'children' => 
      array (
        0 => 'field_aggperiodover4',
        1 => 'field_aggperiodover3',
        2 => 'field_aggart3compliance',
        3 => 'field_aggcompliance',
        4 => 'field_agg_art4_comp_register',
        5 => 'field_aggart6compliance',
        6 => 'field_article_4_compliance_expli',
        7 => 'field_aggart4compliance',
        8 => 'field_agg_art6_comp_register',
        9 => 'field_agg_comp_register',
        10 => 'field_agg_art3_comp_register',
        11 => 'field_agg_art_applied_sa',
        12 => 'field_aggperiodover6',
        13 => 'field_aggart5compliance',
        14 => 'field_article_5_compliance_expli',
        15 => 'field_article_3_compliance_expli',
        16 => 'field_compliance_explication',
        17 => 'field_aggart3addcompliance',
        18 => 'field_aggperiodover5',
        19 => 'field_agg_art5_comp_register',
      ),
       'format_type' => 'tab',
       'format_settings' => 
      array (
        'formatter' => 'closed',
        'instance_settings' => 
        array (
          'description' => '',
          'classes' => '',
          'required_fields' => 1,
        ),
      ),
    )),
    'group_agg_admin' => 
    (object)(array(
       'id' => '46',
       'identifier' => 'group_agg_admin|node|agglomeration|form',
       'group_name' => 'group_agg_admin',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'form',
       'parent_name' => '',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'disabled' => false,
       'label' => 'Agglomeration',
       'weight' => '45',
       'children' => 
      array (
        0 => 'group_agg_system',
        1 => 'group_agg_description',
        2 => 'group_agg_deprecated',
        3 => 'group_agg_links',
        4 => 'group_agg_compliance',
      ),
       'format_type' => 'tabs',
       'format_settings' => 
      array (
        'formatter' => '',
        'instance_settings' => 
        array (
          'classes' => '',
          'id' => '',
        ),
      ),
    )),
  ),
  'default' => 
  array (
    'group_map' => 
    (object)(array(
       'id' => '1',
       'identifier' => 'group_map|node|agglomeration|default',
       'group_name' => 'group_map',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => '',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'map',
       'weight' => '1',
       'children' => 
      array (
        0 => 'field_position_geo',
        1 => 'virtual_field_map',
      ),
       'format_type' => 'div',
       'format_settings' => 
      array (
        'label' => 'map',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => '',
          'description' => '',
          'show_label' => '0',
          'label_element' => 'h3',
          'effect' => 'none',
          'speed' => 'fast',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_forward_looking_aspect' => 
    (object)(array(
       'id' => '39',
       'identifier' => 'group_forward_looking_aspect|node|agglomeration|default',
       'group_name' => 'group_forward_looking_aspect',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => 'group_container2',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'Forward looking aspect',
       'weight' => '16',
       'children' => 
      array (
        0 => 'virtual_field_article_17',
      ),
       'format_type' => 'fieldset',
       'format_settings' => 
      array (
        'label' => 'Forward looking aspect',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-forward-looking-aspect field-group-fieldset col-sm-6',
          'description' => '',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_data_flip_front' => 
    (object)(array(
       'id' => '17',
       'identifier' => 'group_data_flip_front|node|agglomeration|default',
       'group_name' => 'group_data_flip_front',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => 'group_data_flip',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'Data flip front agglomeration',
       'weight' => '7',
       'children' => 
      array (
        0 => 'field_agggenerated',
        1 => 'field_aggcalculation',
        2 => 'field_aggchanges',
        3 => 'field_aggremarks',
        4 => 'field_aggchangescomment',
        5 => 'virtual_field_aggc1_with_pe',
        6 => 'virtual_field_aggc2_with_pe',
        7 => 'virtual_field_aggpercwithouttreatment_with_pe',
      ),
       'format_type' => 'fieldset',
       'format_settings' => 
      array (
        'label' => 'Data flip front agglomeration',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-data-flip-front field-group-fieldset',
          'description' => '',
        ),
        'formatter' => 'collapsible',
      ),
    )),
    'group_container1' => 
    (object)(array(
       'id' => '11',
       'identifier' => 'group_container1|node|agglomeration|default',
       'group_name' => 'group_container1',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => '',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'container_1',
       'weight' => '5',
       'children' => 
      array (
        0 => 'group_site_information',
        1 => 'group_waste_water',
      ),
       'format_type' => 'div',
       'format_settings' => 
      array (
        'label' => 'container_1',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-container1 field-group-div  container',
          'description' => '',
          'show_label' => '0',
          'label_element' => 'h3',
          'effect' => 'none',
          'speed' => 'fast',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_description' => 
    (object)(array(
       'id' => '3',
       'identifier' => 'group_description|node|agglomeration|default',
       'group_name' => 'group_description',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => '',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'Description',
       'weight' => '3',
       'children' => 
      array (
        0 => 'group_description_left',
        1 => 'group_description_right',
      ),
       'format_type' => 'fieldset',
       'format_settings' => 
      array (
        'label' => 'Description',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-description field-group-fieldset container',
          'description' => '',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_data_flip' => 
    (object)(array(
       'id' => '14',
       'identifier' => 'group_data_flip|node|agglomeration|default',
       'group_name' => 'group_data_flip',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => 'group_description_left',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'data flip',
       'weight' => '2',
       'children' => 
      array (
        0 => 'virtual_field_piechart_agglonode',
        1 => 'group_data_flip_front',
      ),
       'format_type' => 'div',
       'format_settings' => 
      array (
        'label' => 'data flip',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'flip',
          'description' => '',
          'show_label' => '0',
          'label_element' => 'h3',
          'effect' => 'none',
          'speed' => 'fast',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_description_right' => 
    (object)(array(
       'id' => '10',
       'identifier' => 'group_description_right|node|agglomeration|default',
       'group_name' => 'group_description_right',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => 'group_description',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'Description Right',
       'weight' => '1',
       'children' => 
      array (
        0 => 'field_aggart3compliance',
        1 => 'field_aggcompliance',
        2 => 'field_aggart6compliance',
        3 => 'virtual_field_aggart4compliance_hierarchical',
        4 => 'virtual_field_aggart5compliance_hierarchical',
        5 => 'virtual_field_table_distance_to_compliance',
      ),
       'format_type' => 'div',
       'format_settings' => 
      array (
        'label' => 'Description Right',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-description-right field-group-div col-sm-6',
          'description' => '',
          'show_label' => '0',
          'label_element' => 'h3',
          'effect' => 'none',
          'speed' => 'fast',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_container2' => 
    (object)(array(
       'id' => '12',
       'identifier' => 'group_container2|node|agglomeration|default',
       'group_name' => 'group_container2',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => '',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'container_2',
       'weight' => '6',
       'children' => 
      array (
        0 => 'group_characteristics',
        1 => 'group_forward_looking_aspect',
      ),
       'format_type' => 'div',
       'format_settings' => 
      array (
        'label' => 'container_2',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-container2 field-group-div container',
          'description' => '',
          'show_label' => '0',
          'label_element' => 'h3',
          'effect' => 'none',
          'speed' => 'fast',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_characteristics' => 
    (object)(array(
       'id' => '5',
       'identifier' => 'group_characteristics|node|agglomeration|default',
       'group_name' => 'group_characteristics',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => 'group_container2',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'Characteristics',
       'weight' => '15',
       'children' => 
      array (
        0 => 'field_aggsuccessor',
        1 => 'field_aggperiodover4',
        2 => 'field_aggforecast',
        3 => 'field_aggperiodover3',
        4 => 'field_aggpercsectreatment',
        5 => 'field_aggaccoverflownumber',
        6 => 'field_aggendlife',
        7 => 'field_aggseweroverflows_m3',
        8 => 'field_agghaveregistrationsystem',
        9 => 'field_aggvideoinspections',
        10 => 'field_aggbesttechnicalknowledge',
        11 => 'field_aggaccoverflows',
        12 => 'field_aggothermeasures',
        13 => 'field_aggpressuretest',
        14 => 'field_aggcapacity',
        15 => 'field_agg_dilution_rates',
        16 => 'field_aggexplanationother',
        17 => 'field_aggmunicipalities',
        18 => 'field_aggseweroverflows_pe',
        19 => 'field_aggpercprimtreatment',
        20 => 'field_aggsewagenetwork',
        21 => 'field_aggpercstringenttreatment',
        22 => 'field_aggbeginlife',
        23 => 'field_aggexistmaintenanceplan',
        24 => 'virtual_field_latitude_custom',
        25 => 'virtual_field_longitude_custom',
        26 => 'virtual_field_aggperiodover5_custom',
      ),
       'format_type' => 'fieldset',
       'format_settings' => 
      array (
        'label' => 'Characteristics',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-characteristics field-group-fieldset col-sm-6',
          'description' => '',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_site_information' => 
    (object)(array(
       'id' => '8',
       'identifier' => 'group_site_information|node|agglomeration|default',
       'group_name' => 'group_site_information',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => 'group_container1',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'Site information',
       'weight' => '27',
       'children' => 
      array (
        0 => 'field_aggnathyperlink',
        1 => 'virtual_field_source_file_link',
      ),
       'format_type' => 'fieldset',
       'format_settings' => 
      array (
        'label' => 'Site information',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-site-information field-group-fieldset col-sm-6',
          'description' => '',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_timeline' => 
    (object)(array(
       'id' => '2',
       'identifier' => 'group_timeline|node|agglomeration|default',
       'group_name' => 'group_timeline',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => '',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'compliance Time Line',
       'weight' => '2',
       'children' => 
      array (
        0 => 'virtual_compliance_time_line',
      ),
       'format_type' => 'fieldset',
       'format_settings' => 
      array (
        'label' => 'compliance Time Line',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-timeline field-group-fieldset',
          'description' => '',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_waste_water' => 
    (object)(array(
       'id' => '6',
       'identifier' => 'group_waste_water|node|agglomeration|default',
       'group_name' => 'group_waste_water',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => 'group_container1',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'Waste Water Network Connexions',
       'weight' => '26',
       'children' => 
      array (
        0 => 'field_agguwwliste',
        1 => 'field_linked_receiving_areas',
        2 => 'field_linked_discharge_points',
        3 => 'field_aggbigid',
        4 => 'field_aggbcliste',
      ),
       'format_type' => 'fieldset',
       'format_settings' => 
      array (
        'label' => 'Waste Water Network Connexions',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-waste-water field-group-fieldset col-sm-6',
          'description' => '',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_graphical' => 
    (object)(array(
       'id' => '4',
       'identifier' => 'group_graphical|node|agglomeration|default',
       'group_name' => 'group_graphical',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => '',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'Graphical network summary',
       'weight' => '4',
       'children' => 
      array (
        0 => 'virtual_graphic',
      ),
       'format_type' => 'fieldset',
       'format_settings' => 
      array (
        'label' => 'Graphical network summary',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-graphical field-group-fieldset container visible-md visible-lg',
          'description' => '',
        ),
        'formatter' => 'open',
      ),
    )),
    'group_description_left' => 
    (object)(array(
       'id' => '9',
       'identifier' => 'group_description_left|node|agglomeration|default',
       'group_name' => 'group_description_left',
       'entity_type' => 'node',
       'bundle' => 'agglomeration',
       'mode' => 'default',
       'parent_name' => 'group_description',
       'table' => 'field_group',
       'type' => 'Normal',
       'export_type' => 1,
       'label' => 'Description left',
       'weight' => '0',
       'children' => 
      array (
        0 => 'group_data_flip',
      ),
       'format_type' => 'div',
       'format_settings' => 
      array (
        'label' => 'Description left',
        'instance_settings' => 
        array (
          'id' => '',
          'classes' => 'group-description-left field-group-div col-sm-6',
          'description' => '',
          'show_label' => '0',
          'label_element' => 'h3',
          'effect' => 'none',
          'speed' => 'fast',
        ),
        'formatter' => 'open',
      ),
    )),
  ),
);