<?php 

$virtual = array (
  'view_modes' => 
  array (
    'teaser' => 
    array (
      'custom_settings' => true,
    ),
    'full' => 
    array (
      'custom_settings' => false,
    ),
    'rss' => 
    array (
      'custom_settings' => false,
    ),
    'token' => 
    array (
      'custom_settings' => false,
    ),
  ),
  'extra_fields' => 
  array (
    'form' => 
    array (
    ),
    'display' => 
    array (
      'virtual_field_error' => 
      array (
        'default' => 
        array (
          'weight' => '0',
          'visible' => true,
        ),
      ),
      'virtual_field_map' => 
      array (
        'default' => 
        array (
          'weight' => '2',
          'visible' => true,
        ),
      ),
      'virtual_field_latitude_custom' => 
      array (
        'default' => 
        array (
          'weight' => '7',
          'visible' => true,
        ),
      ),
      'virtual_field_longitude_custom' => 
      array (
        'default' => 
        array (
          'weight' => '8',
          'visible' => true,
        ),
      ),
      'virtual_field_source_file_link' => 
      array (
        'default' => 
        array (
          'weight' => '12',
          'visible' => true,
        ),
      ),
    ),
  ),
);