<?php 

$virtual = array (
  'view_modes' => 
  array (
    'teaser' => 
    array (
      'custom_settings' => true,
    ),
    'full' => 
    array (
      'custom_settings' => false,
    ),
    'rss' => 
    array (
      'custom_settings' => false,
    ),
    'token' => 
    array (
      'custom_settings' => false,
    ),
  ),
  'extra_fields' => 
  array (
    'form' => 
    array (
      'title' => 
      array (
        'weight' => '1',
      ),
      'path' => 
      array (
        'weight' => '9',
      ),
      'xmlsitemap' => 
      array (
        'weight' => '8',
      ),
    ),
    'display' => 
    array (
      'virtual_field_error' => 
      array (
        'default' => 
        array (
          'weight' => '0',
          'visible' => true,
        ),
      ),
      'virtual_field_map' => 
      array (
        'default' => 
        array (
          'weight' => '2',
          'visible' => true,
        ),
      ),
      'virtual_compliance_time_line' => 
      array (
        'default' => 
        array (
          'weight' => '0',
          'visible' => true,
        ),
      ),
      'virtual_field_data_stackedbar' => 
      array (
        'default' => 
        array (
          'weight' => '43',
          'visible' => true,
        ),
      ),
      'virtual_field_stackedbar_uwwtpnode' => 
      array (
        'default' => 
        array (
          'weight' => '6',
          'visible' => true,
        ),
      ),
      'virtual_field_latitude_custom' => 
      array (
        'default' => 
        array (
          'weight' => '31',
          'visible' => true,
        ),
      ),
      'virtual_field_longitude_custom' => 
      array (
        'default' => 
        array (
          'weight' => '32',
          'visible' => true,
        ),
      ),
      'virtual_field_source_file_link' => 
      array (
        'default' => 
        array (
          'weight' => '9',
          'visible' => true,
        ),
      ),
      'virtual_field_article_17' => 
      array (
        'default' => 
        array (
          'weight' => '7',
          'visible' => true,
        ),
      ),
      'virtual_graphic' => 
      array (
        'default' => 
        array (
          'weight' => '27',
          'visible' => true,
        ),
      ),
    ),
  ),
);