<?php

$list_content_type = array(
    'agglomeration',  //Agglomeration
                      //An area where the population and/or economic activi-ties are sufficiently concentrated for urban waste water to be collected and conducted to an urban waste water treatment plant or to a final discharge point.
                      //Name of the agglomeration
    'uwwtp',         //UWWTP
                    //
                    //Name of UWWTP/ collecting system without treatment
    
    'agglo_uww',    //Agglomeration UWWTP data
                    //
                    //Title
    'big_city',           //Big city
                        //
                        //Name of the big city
    'discharge_point',  //Discharge point
                        //
                        //Name of the discharge point
    'receiving_area',   //Receiving Area
                        //
                        //Name of the Receiving area
    'ms_level',          //MS level
                        //
                        //Title
    'article_17_agglomeration',
    'article_17_uwwtp',
    'article_17_ms_level',
); 