<?php



$country_list = array(
    'at'=>array(
		'CountryName'=>'Austria', 
		'centerpoint' => '16.372 48.208',
		'metadataAggloUid'=> 'f2021b19674505c9cbc51ad27252c89474f2a5c1', 
		'metadataUwwtpUid'=> 'bca0c35f6a6eef7f99a39f91ad9ab42593d4de58', 
		'metadataDpUid'=> '077569cf1eec4fcc60c2ceac84c1b936efb43ed7', 
		'metadataRcaUid'=> 'd1ff869703bed86ba66ef74dacf961885bdba6a2',
        'register_default_rcaType'=>'A54',
	),
    'be'=>array(
        'CountryName'=>'Belgium', 
		'centerpoint' => '4.352042 50.845200',
		'metadataAggloUid'=> '0e37f19cde9cf212d37a6390da2ae0b60c9d4b0d', 
		'metadataUwwtpUid'=> '8f4befd00e7c1733b68706d04a2563ca13737d12', 
		'metadataDpUid'=> '2e766046f8b34747819ad14c82e2c1ef1b6eb3d5', 
		'metadataRcaUid'=> '6d9fe996ca04b560b8751f4a1745cc48b1a4b2c3',
        'register_default_rcaType'=>'NA',
    ),
    'bg'=>array(
		'CountryName'=>'Bulgaria',
		'centerpoint' => '',
		'metadataAggloUid'=> 'bd139988e958b0f46024df55c006039e2e778fe1', 
		'metadataUwwtpUid'=> 'c137b898a180622eba55969c9ee9d472758077fd', 
		'metadataDpUid'=> 'bcbf9579bd4ca47e65d5d47119013d5b49e53b68', 
		'metadataRcaUid'=> '64246917c315a44f01140071ec788415c7586be7',
        'register_default_rcaType'=>'NA',
	),
    'cy'=>array(
        'CountryName'=>'Cyprus', 
		'centerpoint' => '33.388320, 35.190170', 
        'metadataAggloUid'=> 'e3dcd08579cd958bcaa5028b7b5fc99c5b62dcec', 
		'metadataUwwtpUid'=> '0b3d405f94cca841715d2d679a595b0a74bf07d6', 
		'metadataDpUid'=> '395eab5983b1e859a4493559e90de24d47cae488', 
		'metadataRcaUid'=> '5227395618eb647493f2a8c68d06d7cf2449455c' ,
        'register_default_rcaType'=>'NA',
    ),
    'cz'=>array(
		'CountryName'=>'Czech Republic',
		'centerpoint' => '',
		'metadataAggloUid'=> '7522b068ca64f119afb40b421ac69cb312043186', 
		'metadataUwwtpUid'=> '4c1db7ed9a2164b15291ef34f0b6f3d844216de1', 
		'metadataDpUid'=> 'c9e1924988fd8a3c85d34892353f8d11f8a32c03', 
		'metadataRcaUid'=> '2bd2cf0020f884ef9cd7deaadaea1073e3f5d5c9',
        'register_default_rcaType'=>'A58',
	),
    'de'=>array(
		'CountryName'=>'Germany',
		'centerpoint' => '',
		'metadataAggloUid'=> '254948ea36a6b89451473d36a39dcec6a25298c1', 
		'metadataUwwtpUid'=> '54a730ba7545bf690f16bd794e9571dddf732c8c', 
		'metadataDpUid'=> '5859c1fddd4733fb6592f7b1dbe6928d04214275', 
		'metadataRcaUid'=> '6a8e6fd062b07ccb998c88493b126679b531cfb2',
        'register_default_rcaType'=>'A54',
	),
    'dk'=>array(
        'CountryName'=>'Denmark', 
		'centerpoint' => '14.797346, 46.136272',
        'metadataAggloUid' => '754d780e7058e678c31b117bcff9befcf1a87a7e',	
		'metadataUwwtpUid' => '7e6f5442ddea72aa9ebb39fef315aec84586f282',	
		'metadataDpUid' => 'f55088fe7624ffdf8c2f1223f77e2c1f8505be8a',	
		'metadataRcaUid' => '173bf03b748684872c6b05e2d0bb137246dbc2ca',
        'register_default_rcaType'=>'54',
    ),
    'ee'=>array(
		'CountryName'=>'Estonia',
		'centerpoint' => '',
		'metadataAggloUid'=> 'f4ad072f01e3d57b54e2a3810f87b3bc3ccedc89', 
		'metadataUwwtpUid'=> 'db0218f6ec9959ef7d4aec3646d5b467f91f0e9c', 
		'metadataDpUid'=> 'f2c87c1d46a7b758f65d65ad79eff418807d5f42', 
		'metadataRcaUid'=> 'e5c73e8f4c2c73a65c78feb74b1f60e137bd1383',
        'register_default_rcaType'=>'58',
	),
    'es'=>array(
		'CountryName'=>'Spain',
		'centerpoint' => '',
		'metadataAggloUid'=> '5a76ed230213d1ca2b9052904e29d39b6779dba7', 
		'metadataUwwtpUid'=> '532369cd9c7dbb704356ffba35d7fa7d6cd6e985', 
		'metadataDpUid'=> 'edd768dae47fceb3bf77e1f3008754c3f262c2c3', 
		'metadataRcaUid'=> '9c8a14688ebd2597edd5965d6cdba731db24f3d2',
        'register_default_rcaType'=>'NA',
	),
    'fi'=>array(
		'CountryName'=>'Finland',
		'centerpoint' => '',
		'metadataAggloUid'=> '243886bac5b74f19c12fe0822942e5d0c935c99f', 
		'metadataUwwtpUid'=> 'c4dd08ec9f26d876ad9e328759a5fbbf4afe16d3', 
		'metadataDpUid'=> 'f47777a595965f393789aaec4d70c75fc11e2821', 
		'metadataRcaUid'=> '8a24aacdd65cfd42c031562db27ec5294b254758',
        'register_default_rcaType'=>'A58',
	),
    'fr'=>array(
        'CountryName'=>'France', 
		'centerpoint' => '2.4609374564489412, 45.95114971020651',
		'metadataAggloUid'=> '2dd0d7727a8ac93876fb6dea29b72a9b30fa30e8', 
		'metadataUwwtpUid'=> '13aed7e28d2d2ce2bdb08e0515e792c01cf4bb03', 
		'metadataDpUid'=> 'da072d6a64350f4670dd5b723c9fa479aceff822', 
		'metadataRcaUid'=> 'f130608f184825034002bf02f662e6c0758eb521',
        'register_default_rcaType'=>'NA',
    ),
    'gr'=>array(
		'CountryName'=>'Greece',
		'centerpoint' => '',
		'metadataAggloUid'=> '8119c2d6193885ffc944471c015818f0861bc7c2', 
		'metadataUwwtpUid'=> 'ba2d881ba32c6ac880d1254baaf345d9b4ad7437', 
		'metadataDpUid'=> '2d0c9669d0852185652dec4b83deae910893a6e6', 
		'metadataRcaUid'=> '636c2f7b3a140e412b3cbe8dcd7a4543ccacc3f8',
        'register_default_rcaType'=>'NA',
	),
    'hr'=>array(
        'CountryName'=>'Croatia',
		'centerpoint' => '15.971885, 45.825365',
        'metadataAggloUid' => '5b628e65b4c29115ad48a7213bddfa93f05c3352',
		'metadataUwwtpUid' => 'a5ab0d56d60c781b39856299d5a8baaaed3cd1fc',
		'metadataDpUid' => '912a27a10bff193276a5f4fde6422b5ce90a05d7',
		'metadataRcaUid' => '0f7832c51afc43cac0c89899781a399de0b0e04a',
        'register_default_rcaType'=>'NA',
    ),
    'hu'=>array(
		'CountryName'=>'Hungary',
		'centerpoint' => '',
		'metadataAggloUid'=> '4dcb6405960fadc93ed750f93ae989ca32087a18', 
		'metadataUwwtpUid'=> 'cba92874790d359f167182fe049214bbbbef247f', 
		'metadataDpUid'=> 'fdac108238224523706fea3bdbee3f38d2acb8a4', 
		'metadataRcaUid'=> '71ec3c69b04cc208f8367b9bbbddbb9bdd7c067c',
        'register_default_rcaType'=>'NA',
	),
    'ie'=>array(
        'CountryName'=>'Ireland',
		'centerpoint' => '-6.261830, 53.348971',
        'metadataAggloUid' => '1c6b1704fd655459b15dde46aa59f9fb9e89d84b',	
		'metadataUwwtpUid' => 'd15eb23f5bf40de2dea26471b38e68dca0939ade',
		'metadataDpUid' => '891cbde1a01d7e2b4f3c64e7aa04d99f8b92314f',
		'metadataRcaUid' => 'b581c2b264061fc51302685940452b3d436e12bb',
        'register_default_rcaType'=>'NA',
    ),
    'it'=>array(
		'CountryName'=>'Italy',
		'centerpoint' => '',
		'metadataAggloUid'=> 'a31f57ca41adfaf0899dc4a5f51af35cfdc43cd2', 
		'metadataUwwtpUid'=> 'ffc514c459a65249101171000f083c237c97fbfa', 
		'metadataDpUid'=> '0a5bd2dc8496357335d9b67eb33b36c6c0d48f20', 
		'metadataRcaUid'=> 'e796707f9d6b5862a8bba47b41a9926ea4a7aae5',
        'register_default_rcaType'=>'NA',
	),
    'lt'=>array(
        'CountryName'=>'Lithuania', 
		'centerpoint' => '25.244692, 54.693822',
		'metadataAggloUid'=> '73c41570ebaea4dc148dd72c9a5d42dd66e6ea12', 
		'metadataUwwtpUid'=> 'f00b305a9357471b9abc6ce5069ecfb943d14641', 
		'metadataDpUid'=> '1cd450fc53624588ac995cc35dc768eb409fca3e', 
		'metadataRcaUid'=> '00bc96f5094c62af51ce8bc372af1a283bdb6341',
        'register_default_rcaType'=>'A58',
    ),
    'lu'=>array(
		'CountryName'=>'Luxembourg',
		'centerpoint' => '',
		'metadataAggloUid'=> 'f4f167fc811803b081fd24034c2303fbdd2c81de', 
		'metadataUwwtpUid'=> '99928a7bd188d8e5389afca34c07f0ad599cc61e', 
		'metadataDpUid'=> '2eeb4b5af194661d1a817900bcc620c2a75af45a', 
		'metadataRcaUid'=> '42f2897302ee20b91976859d25ae8fdd81615571',
        'register_default_rcaType'=>'A58',
	),
    'lv'=>array(
		'CountryName'=>'Latvia',
		'centerpoint' => '',
		'metadataAggloUid'=> '2d0842dde217fbecce30601c268036d84da43c97', 
		'metadataUwwtpUid'=> '3a4c6c103b848791a4fa6134e91644de2323ad81', 
		'metadataDpUid'=> '9e2d76e7d362b61c0e0808d5df9547cf19439b6b', 
		'metadataRcaUid'=> 'a965784aea3b831d93d2ed237eacbb3e9129ead3',
        'register_default_rcaType'=>'A58',
	),
    'mt'=>array(
		'CountryName'=>'Malta',
		'centerpoint' => '',
		'metadataAggloUid'=> '5ee0d7bb297ca9d131886b6fd29c454733ea82d1', 
		'metadataUwwtpUid'=> 'c4265482e8fe372347a245212c50efe6e1352813', 
		'metadataDpUid'=> 'a4e47e1befd9ed51b15d44091613fda409d9d032', 
		'metadataRcaUid'=> '4a613f0bd4f3abf4e9b86b8f72152f2dff18c883',
        'register_default_rcaType'=>'NA',
	),
    'nl'=>array(
		'CountryName'=>'Netherlands',
		'centerpoint' => '',
		'metadataAggloUid'=> 'f1510e5c39c0f1b6b3c563db7069c16aa449b2e4', 
		'metadataUwwtpUid'=> '6abb7acf484c4dd4e44f11e3dcbb4a81a65ed438', 
		'metadataDpUid'=> '7cd9102981b23438b13f3dafa590df040a78aea1', 
		'metadataRcaUid'=> 'c1d8904cea9dfeb19ba5824be0ac2eb3da1f483a',
        'register_default_rcaType'=>'A54',
	),
    'pl'=>array(
        'CountryName'=>'Poland',
		'centerpoint' => '19.995117147985514, 52.26815738901357',
        'metadataAggloUid' => 'e91553b13416af37cb1c1af4b41df0a69d95af2b',
		'metadataUwwtpUid' => 'fb878c358115854197a77f9771463e8830711aee',
		'metadataDpUid' => '38705496d51f2973e95172657504683dac92580e',
		'metadataRcaUid' => '3b014692338d54a94ee9892afeae6abb90a7d765',
        'register_default_rcaType'=>'A58',
    ),
    'pt'=>array(
		'CountryName'=>'Portugal',
		'centerpoint' => '',
		'metadataAggloUid'=> 'dfd044651fdffa9b2fbab1bd408b2341754e1a13', 
		'metadataUwwtpUid'=> 'c9c0bec3d88b09add15b50da605727b260799c2a', 
		'metadataDpUid'=> '4711898924197ef5100fb8ce5be516bf3fb6d51e', 
		'metadataRcaUid'=> '2c01a3274669ed97e960655f78223598ac1c219e',
        'register_default_rcaType'=>'NA',
	),
    'ro'=>array(
        'CountryName'=>'Romania',
		'centerpoint' => '26.27929681280725, 46.012223874093685',
        'metadataAggloUid' => '0279b40fdf6e847eee8795ec343d9f3f3826bf70',	
		'metadataUwwtpUid' => 'e7cf223294aa2298837fc5c56f139e7f4c4225ae',	
		'metadataDpUid' => '8995e1257d8df55075c82ec7dc26a18801d96351',	
		'metadataRcaUid' => '36503f6d796b7e29c7d96b09ef8c14f400f81dd9',
        'register_default_rcaType'=>'A58',
    ),
    'se'=>array(
		'CountryName'=>'Sweden',
		'centerpoint' => '',
		'metadataAggloUid'=> '7532404b32279986ebbb27205a221d8b4aba05f9', 
		'metadataUwwtpUid'=> '5069b4c75658807579868a5400925d3727294f81', 
		'metadataDpUid'=> '02c9727437756533b969ac23b71b3d01d1cc602c', 
		'metadataRcaUid'=> '7c496505258daa44bb803b40b627e340cdbc0aa9',
        'register_default_rcaType'=>'NA',
	),
    'si'=>array(
        'CountryName'=>'Slovenia',
		'centerpoint' => '14.797346, 46.136272',
        'metadataAggloUid' => '8bbb2d949392820fdc973afe131eebd7e29d0bb5',
		'metadataUwwtpUid' => '8e17c822fbe18debbc0243bebc2399026f7d40d7',
		'metadataDpUid' => 'd136df0a0bc78cb717e13aab577afdaa21f3dccf',
		'metadataRcaUid' => '9f0200694092610e51a3a186f79c157a8a14c3fe',
        'register_default_rcaType'=>'NA',
    ),
    'sk'=>array(
		'CountryName'=>'Slovakia',
		'centerpoint' => '',
		'metadataAggloUid'=> 'ea890b491d4fc2ceac55f74ac5f1986fbc8c3b59', 
		'metadataUwwtpUid'=> '5c95cb90cbfe35f617bb3f1b4c47006fffd282a4', 
		'metadataDpUid'=> 'fb5ee01d853aaac99acdc9cfc648b1cd88481124', 
		'metadataRcaUid'=> '8e97d33670060bf54cb724b82ac4cde9fc137cbd',
        'register_default_rcaType'=>'A54',
	),
    'uk'=>array(
		'CountryName'=>'United Kingdom',
		'centerpoint' => '',
		'metadataAggloUid'=> 'aafa291feca156f1b1a944ee2f215aefb4a51882', 
		'metadataUwwtpUid'=> '53dd80721c6264b18cc46d1c1ee5709b977ac2a2', 
		'metadataDpUid'=> 'd5e1519a67cc986d64512e0a66f8d32c84ad9561', 
		'metadataRcaUid'=> 'ceb8a16066770b99611121c382e917ae34e4f0e8',
        'register_default_rcaType'=>'NA',
	), 
);
define('page_regulations_mask','<h2>European legislation</h2><ul><li><a href="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CONSLEG:1991L0271:20081211:EN:PDF" target="_blank">Directive 91/271/EC Consolidated version </a></li><li><a href="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:31991L0271&amp;from=en" target="_blank">Directive 91/271/EC legal version</a></li><li><a href="http://ec.europa.eu/environment/water/water-urbanwaste/legislation/pdf/transitional_periods_eu10_eu2.pdf" target="_blank">Deadlines of transitional periods for new Member States-EU-12</a></li></ul><h2>National regulations</h2><ul><li>...</li></ul>');
define('page_homepage_mask','Welcome to the Urban Waste Water Treatment Directive (UWWTD) site for :cn !');
define('page_credits_mask','<p>This website was developed by Office International de l’Eau (OIEau) for The <strong>European Commission Directorate General Environment</strong> under Specific contract n°<em>07.0307/2012/638595/D2</em> implementing Framework Service Contract n°ENV.D.2/FRA/2012/0013 It is developed using <em>open source softwares</em>.</p><p>A generic version together with instruction for installation and use can be found here <a href="http://uwwtd.oieau.fr" target="_blank">http://uwwtd.oieau.fr</a></p><p>Copyrights UWWTD-SIIF platform by <strong>Office International de l\'Eau</strong> is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.</p>');
define('block_homepage_mask','Welcome to the Urban Waste Water Directive (UWWTD) Structured Information and Implementation Framework (SIIF) website for :cn . 
The main aim of UWWTD SIIF is to ensure the production and the online dissemination of information allowing:
- the citizens to know the status of implementation of the Directive,
- water stakeholders to access most up to date datasets.
For more details on the UWWTD SIIF framework, look at [URL to concept paper]
The SIIF concept was initially introduced in 2012 through the Commission Communication COM/2012/095 on “Improving the delivery of benefits from EU environment measures: building confidence through better knowledge and responsiveness”. 
It was further elaborated in 2013 for the specific case of Urban Waste Water Directive through a concept paper and its technical annexes.
It was then implemented in 2014 through the current website that give access to information on agglomerations, Urban Waste Water treatment plants, discharge points and sensitive areas, and the associated datasets.');
define('website_mail','bfb@oieau.fr');
define('contact_mail','bfb@oieau.fr');
define('metadata_catalog_url','http://www.uwwtd.oieau.fr/catalogue/srv');

$country_config = array();

foreach($country_list as $cc=>$p){
    $mask =array(
        ':cn'=>$p['CountryName'],
        ':cc'=>$cc
    );
    $search = array_keys($mask);
    $replace = array_values($mask);
    
    $country_config[$cc] = array(      //nicosie
        'website_mail' => website_mail,
        'contact_mail' => contact_mail,
        'name' => $p['CountryName'],
        'openlayers_maps' => array(
              'center' => array(
                'initial' => array(
                  'centerpoint' => isset($p['centerpoint'])?$p['centerpoint']:'4.352042 50.845200',  //longitude, latitude
                  'zoom' => '8',         
                ),
                'restrict' => array(
                  'restrictextent' => 0,
                  'restrictedExtent' => '',
                ),
              ),
              'behaviors' => array(
                'openlayers_behavior_gazetteer' => array(
                  'restriction_query' => 'country='.strtoupper($cc),
                ),              
              ),
            ),        
        'page_regulations' => str_replace($search, $replace, page_regulations_mask),
        'page_homepage' => str_replace($search, $replace, page_homepage_mask),
        'page_credits' => str_replace($search, $replace, page_credits_mask),
        'block_homepage' => str_replace($search, $replace, block_homepage_mask),      
        'metadataAgglo' => metadata_catalog_url,
        'metadataAggloUid' => isset($p['metadataAggloUid'])?$p['metadataAggloUid']:'',
        'metadataUwwtp' => metadata_catalog_url,
        'metadataUwwtpUid' => isset($p['metadataUwwtpUid'])?$p['metadataUwwtpUid']:'',
        'metadataDp' => metadata_catalog_url,
        'metadataDpUid' => isset($p['metadataDpUid'])?$p['metadataDpUid']:'',
        'metadataRca' => metadata_catalog_url,
        'metadataRcaUid' => isset($p['metadataRcaUid'])?$p['metadataRcaUid']:'',
	);
}


   