<?php

$openlayers_styles = new stdClass();
$openlayers_styles->disabled = FALSE; /* Edit this to true to make a default openlayers_styles disabled initially */
$openlayers_styles->api_version = 1;
$openlayers_styles->name = 'discharge_points_style';
$openlayers_styles->title = 'Discharge points style';
$openlayers_styles->description = '';
$openlayers_styles->data = array(
  'pointRadius' => 6,
  'fillColor' => '#ff5656',
  'strokeColor' => '#f36363',
  'strokeWidth' => 1,
  'fillOpacity' => 0.9,
  'strokeOpacity' => 0.9,
  'strokeLinecap' => 'round',
  'strokeDashstyle' => 'solid',
  'graphicOpacity' => 1,
  'labelAlign' => 'cm',
);
