<?php

$openlayers_styles = new stdClass();
$openlayers_styles->disabled = FALSE; /* Edit this to true to make a default openlayers_styles disabled initially */
$openlayers_styles->api_version = 1;
$openlayers_styles->name = 'triangle_violet';
$openlayers_styles->title = 'Triangle violet';
$openlayers_styles->description = '2015/10/15 11:06:45
2015-10-15 11:06:45';
$openlayers_styles->data = array(
  'pointRadius' => 6,
  'fillColor' => '#da70d6',
  'strokeColor' => '#EE9900',
  'strokeWidth' => 1,
  'fillOpacity' => 0.9,
  'strokeOpacity' => 0.9,
  'strokeLinecap' => 'round',
  'strokeDashstyle' => 'solid',
  'graphicOpacity' => 1,
  'labelAlign' => 'cm',
);
