<?php

$openlayers_styles = new stdClass();
$openlayers_styles->disabled = FALSE; /* Edit this to true to make a default openlayers_styles disabled initially */
$openlayers_styles->api_version = 1;
$openlayers_styles->name = 'waste_water_treatment_plant_style';
$openlayers_styles->title = 'Waste water treatment plant style';
$openlayers_styles->description = date('Y-m-d H:i:s');
$openlayers_styles->data = array(
  'pointRadius' => 6,
  'fillColor' => '#79e0fa',
  'strokeColor' => '#77cee4',
  'strokeWidth' => 1,
  'fillOpacity' => 0.9,
  'strokeOpacity' => 0.9,
  'strokeLinecap' => 'round',
  'strokeDashstyle' => 'solid',
  'graphicOpacity' => 1,
  'labelAlign' => 'cm',
);
