<?php

/**
 * @file
 * Main file of this module. Loads include files and implements general hooks.
 */

module_load_include('inc', 'gdal', '/includes/GdalModuleException');
module_load_include('inc', 'gdal', '/includes/OgrFeatureIterator');
module_load_include('inc', 'gdal', '/includes/OgrReader');
module_load_include('inc', 'gdal', '/includes/SpatialReference');
module_load_include('inc', 'gdal', '/includes/feeds/FeedsOgrParser');
module_load_include('inc', 'gdal', '/includes/feeds/OgrFeedsParserResult');

/**
 * Implements ctools_plugin_api().
 */
function gdal_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function gdal_feeds_plugins() {
  $info = array();
  $info['FeedsOgrParser'] = array(
    'name' => 'Vector geodata parser',
    'description' => 'Parse vector geodata feeds.',
    'help' => 'Use the GDAL/OGR library to parse OGR geodata feeds.',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'FeedsOgrParser',
      'file' => 'FeedsOgrParser.inc',
      'path' => drupal_get_path('module', 'gdal').'/includes/feeds/',
    ),
  );
  return $info;
}

// vim: ft=php tabstop=2 shiftwidth=2
